### ISSUE TITLE
Frozen on 'loading' page when deployed

### ISSUE THREAD

**Issue by anirudhvenu** [NUS-ALSET/lti-starter#4]
Upon completing the install instructions and opening the Firebase link to the project, the result is as shown and does not move past this loading page.  I followed the steps as described but is there something else that I may be missing?

![screenshot-2018-1-14 react app](https://user-images.githubusercontent.com/20701981/34915915-bd07edf6-f969-11e7-828a-33fca45845b3.png)

**Comment by ihands** [comment]
Need to merge code from Pull Request, rebuild and deploy it again.

**Comment by ihands** [comment]
Did you update and deploy it?
