### ISSUE TITLE
Change default parameter in .firebaserc

### ISSUE THREAD

**Issue by anirudhvenu** [NUS-ALSET/lti-starter#5]
The default parameter in **.firebaserc** should be changed to application name in order to avoid access right violations.

```
{
  "projects": {
    "default": "lti-starter" \\ Otherwise the default is: fir-lti-35fdc 
  }
}
```

I was facing this error and it was resolved when I set the default value to my application name (lti-starter).

Corresponding update to the README should be made if this is the case.

**Comment by ihands** [comment]
I think that it's not a case. We can leave it empty.

When we run 

$ firebase use --add
$ firebase use <alias_or_project_id>

This command will ask you to choose a Firebase project ID and the default value will be updated accordingly.

Check details at https://firebase.google.com/docs/cli/
